# Generated by Django 5.1 on 2025-04-07 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('rec_app', '0002_rename_immmobilising_plaster_cast_riskfactor2_immobilising_plaster_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentchart',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_charts', to='patients.patient'),
        ),
    ]
