# Generated by Django 5.1 on 2025-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0003_alter_treatmentchart_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentchart',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='treatmentchart',
            name='medicines',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
