# Generated by Django 5.1 on 2025-04-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0004_remove_treatmentchart_medicine_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentchart',
            name='medicines',
        ),
        migrations.AddField(
            model_name='treatmentchart',
            name='medicine_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
