# Generated by Django 5.2 on 2025-05-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
